# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='numbe_per_menu',
            new_name='number_per_menu',
        ),
    ]
