# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0003_select_food_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Select_food_list',
            new_name='FoodList',
        ),
    ]
